### ISSUE TITLE
Regular error from UI on ridge/skeletonize pipeline

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/histonets-cv#151]
In the post-process stage of the UI, which runs `ridges` and `skeletonize`, we regularly get the following error, depending on parameter values: 

```ValueError: threshold_li is expected to work with images having more than one value. The input image seems to have just one value 0.```

We need to better handle this in both the CLI and UI.

**Comment by csbailey5t** [comment]
Here is an example map image that can be used to test particular params. An example of params that throw the above error is: `'[{"action":"ridges","options":{"width":6,"threshold":10,"dilation":3}},{"action":"skeletonize","options":{"method":"combined","dilation":13,"binarization-method":"li"}}]'`

![small_map_4ff395ae19d273f19f90fa664ce2ddae_1d150a_5e6162_6c1a03_bc1400_tmp](https://user-images.githubusercontent.com/4672869/28689881-082cabac-72cc-11e7-89a8-07e48ab02cf9.png)

**Comment by versae** [comment]
The main issue here is that with those values for the ridge detector the result is a black image, therefore there is nothing to skeletonize. Better arguments could be `'[{"action":"ridges","options":{"width":10,"threshold":128,"dilation":0}},{"action":"skeletonize","options":{"method":"combined","dilation":1,"binarization-method":"li"}}]'`.

One approach could be to ignore black images in the skeletonize command.

**Comment by csbailey5t** [comment]
These params do seem to help in the UI to get a better post processed image, but, unfortunately, still cause the tests to regularly fail with the same error.
