### ISSUE TITLE
Negative values are considered options for the CLI

### ISSUE THREAD

**Issue by versae** [sul-cidr/histonets-cv#52]
When trying to pass negative values for subcommands such as contrast, negative values are parsed as options, thus failing when trying to find the corresponding ones.
```
histonets contrast -5
```

**Comment by csbailey5t** [comment]
Would the best way to handle this be to rescale the functions so they only take positive values (0 to 200 perhaps instead of -100 to 100)? Does that still make sense from a user perspective for adjusting contrast and brightness?

**Comment by versae** [comment]
It seems like that will be the solution. Let me see if I can find a way to bypass those numbers in `Click`.

**Comment by versae** [comment]
Apparently `Click` got it covered. The way to pass negative numbers is by preceding them with a double dash `--`. So
```
histonets contrast -50
```
Becomes
```
histonets contrast -- -50
```
They claim is the UNIX way.

**Comment by csbailey5t** [comment]
Yeah, I knew you could do that in Bash, but wasn't sure what the easy way to do it in click is. Is there a method/option to use, or do you just add the extra dashes to the argument @versae ?
