### ISSUE TITLE
Can you please confirm the default parameters that should yield an unscathed image?

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets-cv#73]
Currently, I'm running this command:

```sh
$ histonets pipeline '[{"action":"denoise","options":{"value":0}},{"action":"equalize","options":{"value":0}},{"action":"brightness","options":{"value":100}},{"action":"contrast","options":{"value":100}},{"action":"smooth","options":{"value":0}}]' file://./tests/images/test.jpg -o /tmp/new_test.jpg
```

And it seems to be taking a while. Do I have the default parameters correct here?

**Comment by mejackreed** [comment]
Now confirmed I'm not getting back the same image. It appears "brighter"

**Comment by mejackreed** [comment]
so some preliminary tests:

 - denoise  - takes a while by itself at `0`
 - equalize - seems to modify the image at `0`

brightness, contrast, and smooth appear quick and no-op at defaults

This isn't scientific, but my perception so far

**Comment by versae** [comment]
In the API the code is correct, but the CLI should just do nothing when passed the default values.

**Comment by csbailey5t** [comment]
This seems to be primarily an issue with the UI and how we the commands in the Rails app. For someone using the CLI itself or the library directly, they wouldn't run commands in the pipeline that they don't need, so the defaults don't really matter. 

It seems like the best solution might be to make sure that in the Rails app we only add an action to the pipeline if the value on the slider is something other than the default for smooth, denoise, equalize, and posterize. That would mean building the pipeline command, or the json fed into the pipeline, based on changes in the UI.

**Comment by csbailey5t** [comment]
See https://github.com/sul-cidr/histonets/issues/67
