### ISSUE TITLE
New issue: when referencing local file, raising an error

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets-cv#75]
```sh
histonets contrast 50 file://./spec/fixtures/images/eddie.jpg -o ./spec/fixtures/images/eddie_contrast_tmp.jpg
```

yields:

`Error: Invalid value for "image": encoding with 'idna' codec failed (UnicodeError: label empty or too long)`

**Comment by mejackreed** [comment]
This doesn't seem to be happening when using a remote image

**Comment by csbailey5t** [comment]
It looks like the file adapter can't handle the leading `./`. If I try a similar command: `histonets contrast 50 file://./tests/images/test.png`, I get the same error you did. If I run it as `histonets contrast 50 file://tests/images/test.png`, it works fine.

**Comment by mejackreed** [comment]
Ah perfect thanks! Thats strange as it seemed to be working previously /shrug. But thanks that resolved the issue.
